### ISSUE TITLE
KeepLayout add  LDProgressView BLANK

### ISSUE THREAD

**Issue by sd1435728** [iMartinKiss/KeepLayout#64]
code:
  _contentView=[[UIScrollView alloc]init];
    [self.view addSubview:_contentView];
    _contentView.backgroundColor=[UIColor whiteColor];
    _contentView.keepInsets.equal=0;

    
    LDProgressView  *progressView=[self createProgress];
    [_contentView addSubview:progressView];
    progressView.keepHeight.equal=20;
    progressView.keepLeftInset.equal=10;
    progressView.keepRightInset.equal=10;
    progressView.keepTopInset.equal=50;
LDProgressView  Unable to display?

**Comment by iMartinKiss** [comment]
Can you describe what is the actual issue? What do yo expect and what do you get?

**Comment by sd1435728** [comment]
_contentView=[[UIScrollView alloc]init];
[self.view addSubview:_contentView];
_contentView.backgroundColor=[UIColor whiteColor];
_contentView.keepInsets.equal=0;

LDProgressView  *progressView=[self createProgress];
[_contentView addSubview:progressView];
progressView.keepHeight.equal=20;
progressView.keepLeftInset.equal=10;
progressView.keepRightInset.equal=10;
progressView.keepTopInset.equal=50;

hello，sorry,My English is very poor，As shown in the above code，LDProgressView Can't show。
but，i code   progressView.frame Do not use keepLayout，It's normal，I don't quite understand what is the problem
