### ISSUE TITLE
KeepTypes.h does not compile in projects iOS > 7

### ISSUE THREAD

**Issue by fernandodev** [iMartinKiss/KeepLayout#65]
Hi,

because these constants:
```objective-c
static const UILayoutPriority UILayoutPriorityRequired NS_AVAILABLE_IOS(6_0) = 1000; // A required constraint.  Do not exceed this.
static const UILayoutPriority UILayoutPriorityDefaultHigh NS_AVAILABLE_IOS(6_0) = 750; // This is the priority level with which a button resists compressing its content.
static const UILayoutPriority UILayoutPriorityDefaultLow NS_AVAILABLE_IOS(6_0) = 250; // This is the priority level at which a button hugs its contents horizontally.
static const UILayoutPriority UILayoutPriorityFittingSizeLevel NS_AVAILABLE_IOS(6_0) = 50; // When you send -[UIView systemLayoutSizeFittingSize:], the size fitting most closely 
```

the header breaks the compilation

**Comment by iMartinKiss** [comment]
Because they are not integers anymore? Are you using the latest `master` revision? This has been fixed a long time ago.

**Comment by fernandodev** [comment]
I'm using `master` version via `cocoapods`. 

I believe that the problem is `NS_AVAILABLE_IOS(6_0)`. My project is iOS > 7, so `NS_AVAILABLE_IOS(6_0)` will not work

**Comment by asifbilal-vteams** [comment]
I am using cocoa Pods for this. And am having the same issue.

**Comment by fjcaetano** [comment]
It seems the project is not being updated on Cocoapods' Specs repo. The latest version there is 1.2.2:

https://cocoapods.org/?q=keeplayout

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <Re: [KeepLayout] KeepTypes.h does not compile in projects iOS > 7 (#65)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by iMartinKiss** [comment]
I regret ever starting support for CocoaPods. Learn how to link your Pods file directly to this repo.
