### ISSUE TITLE
Align a view on the bottom of another view.

### ISSUE THREAD

**Issue by andreesurya** [iMartinKiss/KeepLayout#66]
Hi there, I'm sorry for asking such a simple question, but I can't infer this from the README file alone. How to place a view on the bottom of another view?

This doesn't seem to work.
```
view2.keepTopTo(view1.keepBottom)
```

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <[KeepLayout] Align a view on the bottom of another view. (#66)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by iMartinKiss** [comment]
I think you are looking for _Offset_:

```objc
view2.keepTopOffsetTo(view1).equal = 0;
```

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <Re: [KeepLayout] Align a view on the bottom of another view. (#66)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by andreesurya** [comment]
That's it, thanks!
