### ISSUE TITLE
What's wrong with the cocoaPods .

### ISSUE THREAD

**Issue by LeeLux** [iMartinKiss/KeepLayout#69]
pod search keeplayout

-> KeepLayout (1.2.2)
   Making Auto Layout easier to code.
   pod 'KeepLayout', '~> 1.2.2'
   - Homepage: https://github.com/iMartinKiss/KeepLayout
   - Source:   https://github.com/iMartinKiss/KeepLayout.git
   - Versions: 1.2.2, 1.2.1, 1.1.1, 1.0.2, 1.0.1, 0.3.1, 0.3.0 [master repo]

**Comment by iMartinKiss** [comment]
I’m no longer updating CocoaPods central repo.

    pod 'KeepLayout', :git => 'https://github.com/iMartinKiss/KeepLayout.git'

**Comment by LeeLux** [comment]
Tks
