### ISSUE TITLE
Set Proportional Width / Height To Another View

### ISSUE THREAD

**Issue by RuCray** [iMartinKiss/KeepLayout#71]
Is there a way to set proportional width / height to another view with KeepLayout?

**Comment by sunhr** [comment]
UIView *view1;
    UIView *view2;
    
    [self.view addSubview:view1];
    [self.view addSubview:view2];
    
    view1.keepWidthTo(view2).equal = 0.5;
    view1.keepHeightTo(view2).equal = 0.8;
